spring.application.name=zalexHumanResources
spring.config.import=optional:configserver:
spring.datasource.url=jdbc:postgresql://localhost:5432/zalex_hr
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
